// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fppxvizwttgcsydkxkdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcHh2aXp3dHRnY3N5ZGt4a2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTEzNjAsImV4cCI6MjA2NjI2NzM2MH0.9q6irUWi90ebWlU3VuoK3cMtyc3wgChnIDQiQDrxbQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);